reference: "/data/sam/analysis/PansimNuc/parameter_sweep/exon_mu_high_recombination_none_selection_none/root.fasta"
input_dir: "/data/sam/analysis/PansimNuc/parameter_sweep/exon_mu_high_recombination_none_selection_none"
output_dir: "/data/sam/analysis/PansimNuc/parameter_sweep/exon_mu_high_recombination_none_selection_none/pg_results"
fasta_extensions: [".fasta", ".fa", ".fna"]

# minimap2 alignment preset. Options: asm5 (<1% divergence), asm10 (<10%), asm20 (<20%)
minimap2_preset: "asm5"

# paftools parameters for variant calling.
paftools_preset: "-l 1 -L 1"

# variant calling parameters
variant_calling_min_mapping_quality: 0
variant_calling_min_quality: 20

# plink parameters for LD pruning. Set plink_ld_window to a large number to disable window-based pruning and only use plink_ld_window_kb.
plink_ld_window: 99999
plink_ld_window_kb: 1000

# pegas parameters for recombination detection
pegas_recombination_threshold: 0.9

# set to true to enable simulation-specific analyses (plot_haplotypes, plot_te_copy_numbers, plot_sv, print_DFEs)
simulated: True
haplotypes_top_n: 5    # top N haplotypes to retain in haplotype plots (0 = keep all)
