reference: "root.fasta"
input_dir: "analysis"
output_dir: "results"
fasta_extensions: [".fasta", ".fa", ".fna"]

# minimap2 alignment preset. Options: asm5 (<1% divergence), asm10 (<10%), asm20 (<20%)
minimap2_preset: "asm5"

variant_calling:
  min_mapping_quality: 0
  min_quality: 20

plink:
  ld_window: 99999
  ld_window_kb: 1000

pegas:
  recombination_threshold: 0.9
